pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
   
            steps {
                echo "Compiling and running Java HelloWorld program..."
                sh 'mvn clean compile'
                sh 'java -cp target/classes com.example.HelloWorld'
            }
        

       
            steps {
                echo "Running unit tests..."
                sh 'mvn test'
            }
        }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
